///
/// Stride-128 inverse-NTT (Gentleman-Sande) butterfly stage.
///
/// Generated by `whittle emit gs --stride 128` from the derived
/// mod-q reduction schedule; SLOTHY-ready (see mlkem-selkie's
/// tools/slothy/README.md).
///
/// Per butterfly:
///   sum  = vj + vjl
///   diff = vjl - vj
///   out_lo = sum                        (no reduction: whittle schedule)
///   out_hi = barrett_const_mul(diff, zeta, zeta_bar)          (3 vec ops)
///
/// 2-butterfly interleave over 8 iterations. Loop body advances ptr
/// by 32 bytes per pass; upper half stays at +256.
///
///   x0  = ptr to 512-byte window
///   w1  = zeta
///   w2  = zeta_bar
///
/// Constant registers set by prologue:
///   v28 = zeta broadcast (i16 x 8)
///   v29 = zeta_bar broadcast (i16 x 8)
///   v30 = Q (i16 x 8) — used by barrett_const_mul's mls
///

.text
.global intt_stride128
.type intt_stride128, %function
intt_stride128:
        dup     v28.8h, w1
        dup     v29.8h, w2
        mov     w9,     #3329
        dup     v30.8h, w9

        mov     x9,     #8

intt_stride128_start:
        ldp     q0,  q1,  [x0, #0]             // vj_a,  vj_b
        ldp     q2,  q3,  [x0, #256]           // vjl_a, vjl_b

        // sum = vj + vjl ; diff = vjl - vj
        add     v4.8h, v0.8h, v2.8h            // sum_a
        sub     v6.8h, v2.8h, v0.8h            // diff_a
        add     v5.8h, v1.8h, v3.8h            // sum_b
        sub     v7.8h, v3.8h, v1.8h            // diff_b

        // barrett_const_mul(diff_a, zeta, zbar) -> v20
        mul     v20.8h, v6.8h, v28.8h          // t   = diff * zeta
        sqrdmulh v21.8h, v6.8h, v29.8h         // s   = qrdmulh(diff, zbar)
        mls     v20.8h, v21.8h, v30.8h         // t  -= s * Q

        // barrett_const_mul(diff_b, zeta, zbar) -> v22
        mul     v22.8h, v7.8h, v28.8h
        sqrdmulh v23.8h, v7.8h, v29.8h
        mls     v22.8h, v23.8h, v30.8h

        stp     q4, q5, [x0], #32              // out_lo pair, post-increment
        stp     q20, q22, [x0, #224]           // out_hi pair at (base+256-32)

        sub     x9, x9, #1
        cbnz    x9, intt_stride128_start

        ret
